services:
  db:
    image: postgres:17
    container_name: dashboard_task
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard-tasks
    ports:
      - '5432:5432'
